### ISSUE TITLE
mod_lua.cpp:202 /usr/local/freeswitch/scripts/utf8.lua:6: module 'ffi' not found:

### ISSUE THREAD

**Issue by ayuraj736** [luapower/utf8#3]
HI I want to convert my normal text to utf8 encoded string and trying to use utf8.lua and utf8_test.lua but I am getting some errors 
can you please check and give me the solution
 [ERR] mod_lua.cpp:202 /usr/local/freeswitch/scripts/utf8.lua:6: module 'ffi' not found:
        no field package.preload['ffi']
        no file '/usr/local/freeswitch/scripts/ffi.lua'
        no file '/usr/local/share/lua/5.2/ffi.lua'
        no file '/usr/local/share/lua/5.2/ffi/init.lua'
        no file '/usr/local/lib/lua/5.2/ffi.lua'
        no file '/usr/local/lib/lua/5.2/ffi/init.lua'
        no file '/usr/share/lua/5.2/ffi.lua'
        no file '/usr/share/lua/5.2/ffi/init.lua'
        no file './ffi.lua'
        no file '/usr/local/lib/lua/5.2/ffi.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ffi.so'
        no file '/usr/lib/lua/5.2/ffi.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './ffi.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/freeswitch/scripts/utf8.lua:6: in main chunk
        [C]: in function 'require'

**Comment by capr** [comment]
Hi, this is a library for LuaJIT, won't work with Lua 5.2.

**Comment by ayuraj736** [comment]
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
The version above I am using this will not work with LuaJIT 
Are you saying I can't use your code with my current lua version

**Comment by capr** [comment]
Yes, many libraries are LuaJIT-only as they use the ffi module, eg. see https://luapower.com/utf8

**Comment by ayuraj736** [comment]
so if I'll install LUAJIT externally will it work then?

**Comment by capr** [comment]
Unfortunately no, you'll have to run all your code with LuaJIT, but then you'll get Lua 5.1 + some features from Lua 5.2 but not full compatibility with Lua 5.2.
